name: Marsvin matrix library check jobs
on:
  pull_request:
    branches:
      - main
jobs:
  build-project:
    name: Build and Run unit-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..
          make
  clang-format-check:
    name: Run clang-format-15
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format-15
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main"
          sudo apt-get update
          sudo apt-get install -y clang-15 clang-format-15
      - name: Run clang-format-15 in source code
        run: |
          clang-format-15 --Werror --dry-run core/**/*.*pp

